name: Rustfmt
on: [push, pull_request]
jobs:
  test:
    name: Rust ${{matrix.rust}}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt
      - name: Run rustfmt
        run: cargo fmt --all -- --check
